[package]
name = "TryToFindX"
version = "0.2.0"
edition = "2021"

[dependencies]
string_calculator = "0"
rust_decimal = "1"
regex = "1"

[profile.release]
strip = "symbols"
lto = "thin"
panic = "abort"
opt-level = 3
